stages:
  - build

#services:
#  - docker:18.03-dind
## TODO: Create branch called ci and test changes to this CI file.  Discard the branch when done testing and checkout main again
#variables:
#  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: tcp://localhost:2375
#  DOCKER_TLS_CERTDIR: ""


Build Image:
  stage: build
  only:
    - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  #rules:
  #  - if: $CI_COMMIT_TAG
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:latest
